### ISSUE TITLE
pip install failed

### ISSUE THREAD

**Issue by starplanet** [pinterest/thrift-tools#12]
pip install failed, it will throw following error:

```shell
Collecting scapy==2.3.1 (from thrift-tools)
  Downloading http://mirrors.aliyun.com/pypi/packages/ee/cd/d20c1e121b09697bf4d7b1b9edde6573fc7d54eefc56860f457a7edfc0de/scapy-2.3.1.zip (1.1MB)
    100% |████████████████████████████████| 1.1MB 296kB/s
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-aaaly1sw/scapy/setup.py", line 35
        os.chmod(fname,0755)
```

The problem is caused by scapy library which has a bug in setup.py at version 2.3.1 when using python 3.7+ version. thrift-tools package should change scapy version to a higher version.

**Comment by rgs1** [comment]
@starplanet we can update to scapy latest... but we don't currently support python 3.7 though.

**Comment by rgs1** [comment]
@starplanet new release here: https://pypi.org/project/thrift-tools/.

I'll try to get started on py3 support....  patches welcomed tho :-)
