### ISSUE TITLE
Can thrift traffic be replayed via thrift-tools?

### ISSUE THREAD

**Issue by dreamyeah** [pinterest/thrift-tools#19]
thrift-tools is a library and a set of tools to introspect Apache Thrift traffic.
Can thrift traffic be replayed via thrift-tools?
if not, can add new features for traffic replay？

**Comment by rgs1** [comment]
@dreamyeah currently it doesn't have a way to replay traffic... I think https://github.com/pinterest/bender is a better option for that.

**Comment by rgs1** [comment]
Closing for now, but happy to help/review PRs related to an integration with bender.
