### ISSUE TITLE
Support thrift 0.10.0

### ISSUE THREAD

**Issue by vtatai** [pinterest/thrift-tools#8]
We have several services written in 0.10.0 and would love to be able to use thrift-tools. Is this still being actively supported?

**Comment by rgs1** [comment]
@vtatai hi! sorry for the late reply, yes thrift-tools is actively supported. Were you planning on working for thrift 0.10.0 support yourself or wondering if someone is working on it?

**Comment by rgs1** [comment]
We now support thrift `0.11.0`.
